#!/usr/bin/env bash

# Checks to see if we're running as sudo.
# Returns 0 if running as sudo, and returns 1 if not.
checkForSudo() {
    if [ "$(id -u)" != "0" ]; then
        return 1
    else
        return 0
    fi
}

