#!/usr/bin/env bash

# Immediately stop on any command that fails
set -e

find . -maxdepth 3 -name ".git" | while read -r line; do
    (
        dirToUpdate=$line

        # Remove the ".git" from the end of the path.
        #dirToSync="${line: : -4}"
        dirToUpdate="${dirToUpdate::${#dirToUpdate}-4}"

        # Remove the "./" at the beginning of the path.
        #dirToSync="${dirToSync:2}"
        dirToUpdateClean="${dirToUpdate:2}"

        # Remove trailing "/" so it looks nicer in the output.
        #dirToSyncClean="${dirToSync: : -1}"
        dirToUpdateClean="${dirToUpdateClean::${#dirToUpdateClean}-1}"

        echo "===== Processing folder: '$dirToUpdateClean' ====="

        cd "$dirToUpdate" || exit
        git pull | while read -r line; do 
            echo "[$dirToUpdateClean] $line"
        done
    )
done

