#!/usr/bin/env bash

set -e
#set -x

packages=""

for package in $(npm outdated -g --parseable --depth=0 | cut -d: -f4)
do
    packages+="$package "
done

if [[ -z "$packages" ]]; then
    echo "All NPM pacakges are up to date!"
else
    pacakges="${packages: : -1}"
    echo "Upgrading pacakges: $packages"
    npm install -g "$packages"
fi

