#!/usr/bin/env bash

# The -e flag makes it so if a command exits with an error and the caller does not check such error, the script aborts immediately.
# Bash strict mode.
set -eEo pipefail

packages=""

for package in $(npm outdated -g --parseable --depth=0 | cut -d: -f4)
do
    packages+="$package "
done

if [[ -z "$packages" ]]; then
    echo "All NPM pacakges are up to date!"
else
    pacakges="${packages: : -1}"
    echo "Upgrading pacakges: $packages"
    npm install -g "$packages"
fi

