#!/usr/bin/env bash

set -e
#set -x

for package in $(npm outdated -g --parseable --depth=0 | cut -d: -f3)
do
    packages+="$package "
done

if [[ -z "$packages" ]]; then
    echo "All NPM pacakges are up to date!"
else
    #packages="${packages: : -1}"
    packages="$(echo $packages | sed 's/ *$//')"
    echo "Upgrading pacakges: $packages"
    npm install -g "$packages"
fi

