#!/usr/bin/env bash

# 1. Change to the `$NVM_DIR`.
# 2. Pull down the latest changes.
# 3. Check out the latest version.
# 4. Activate the new version.

(
  cd "$NVM_DIR"
  git fetch origin
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
) && . "$NVM_DIR/nvm.sh"

