#!/usr/bin/env bash

# The -e flag makes it so if a command exits with an error and the caller does not check such error, the script aborts immediately.
# Bash strict mode.
set -eEo pipefail

dpkg -l | grep '^rc' | awk '{print $2}' | xargs sudo apt-get purge -y

