#!/bin/bash

# One liner for getting the location of where this script is.
workingDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Import stuffs.
. "$workingDir/check-for-sudo"
. "$workingDir/check-for-command-existance"

# Run update and upgrade.
updateAndUpgradeApt() {
    checkForCommandExistence "apt"
    apt update
    apt upgrade
}

# Runs flatpak update.
updateFlatpak() {
    checkForCommandExistence "flatpak"
    flatpak update
}

# Runs npm-check on global.
updateNpmGlobal() {
    checkForCommandExistence "npm-check"
    npm-check -gu
}

# Attempts to refresh all snaps.
updateSnaps() {
    checkForCommandExistence "snap"
    snap refresh
}

if checkForSudo; then
    updateAndUpgradeApt
    updateFlatpak
    updateNpmGlobal
    updateSnaps
else
    #echo "Please run me as root!"
    # Just run the current command with sudo.
    sudo "$0" "$@"
fi

