#!/usr/bin/env bash

# Returns 0 if versions are euqal, 1 if first version is greater than second, and 2 if second version is greater than first.
versionCompare () {
    leftHandSide="$1"
    rightHandSide="$2"

    if [[ "$leftHandSide" == "$rightHandSide" ]]; then
        return 0
    fi

    if [[ "$leftHandSide" == "v"* ]]; then
        leftHandSide=${leftHandSide#"v"}
    fi

    if [[ "$rightHandSide" == "v"* ]]; then
        rightHandSide=${rightHandSide#"v"}
    fi

    local IFS=.
    local i ver1=($leftHandSide) ver2=($rightHandSide)

    # Fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
        ver1[i]=0
    done

    for ((i=0; i<${#ver1[@]}; i++)); do
        if [[ -z ${ver2[i]} ]]; then
            # Fill empty fields in ver2 with zeros
            ver2[i]=0
        fi

        if ((10#${ver1[i]} > 10#${ver2[i]})); then
            return 1
        fi

        if ((10#${ver1[i]} < 10#${ver2[i]})); then
            return 2
        fi
    done

    return 0
}

